name: Quality checks 👌🧪

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
  merge_group:
  workflow_dispatch:

jobs:
  dependency-review:
    name: Vulnerable dependencies 🔎
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7
        with:
          show-progress: false

      - name: Scan
        uses: actions/dependency-review-action@v4.3.4
        with:
          ## Workaround from https://github.com/actions/dependency-review-action/issues/456
          ## TODO: Remove when necessary
          base-ref: ${{ github.event.pull_request.base.sha || 'master' }}
          head-ref: ${{ github.event.pull_request.head.sha || github.ref }}

  lint:
    name: Lint 🔬
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.7
        with:
          show-progress: false

      - name: Setup node environment ⚙️
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          check-latest: true

      - name: Install dependencies 📦
        run: npm ci --no-audit

      - name: Run linter ✏️
        run: npm run lint

  typecheck:
    name: Typecheck 🈯
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.7
        with:
          show-progress: false

      - name: Setup node environment ⚙️
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          check-latest: true

      - name: Install dependencies 📦
        run: npm ci --no-audit

      - name: Run typecheck 📖
        run: npm run typecheck

  build:
    name: Build 🏗️
    uses: ./.github/workflows/package.yml
    with:
      commit: ${{ github.sha }}

  conventional_commits:
    name: Conventional commits check 💬
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v4.1.7
        with:
          show-progress: false

      - name: Check if all commits comply with the specification
        uses: webiny/action-conventional-commits@v1.3.0
